export type IconCategory =
  | "Communication"
  | "Editor"
  | "Feedback"
  | "Files"
  | "General"
  | "Interaction"
  | "Logo"
  | "Media"
  | "Time"
  | "Users";

/**
 * Figma의 `icon` ComponentSet variant `type=` 값을 카테고리에 매핑한다.
 * 디자이너 Figma 페이지의 시각적 카테고리 frame을 그대로 따른다.
 */
export const ICON_CATEGORIES: Record<string, IconCategory> = {
  archive: "Communication",
  birth: "Communication",
  bookmark: "Communication",
  edit: "Communication",
  eye: "Communication",
  eyeOff: "Communication",
  location: "Communication",
  mail: "Communication",
  mento: "Communication",
  mesageCheck: "Communication",
  message: "Communication",
  messageAlert: "Communication",
  messageChat: "Communication",
  messageDots: "Communication",
  messagePlus: "Communication",
  messageQuestion: "Communication",
  messageText: "Communication",
  messageX: "Communication",
  phone: "Communication",
  pin: "Communication",
  send: "Communication",

  alignCenter: "Editor",
  alignJustify: "Editor",
  alignLeft: "Editor",
  alignRight: "Editor",
  attachment: "Editor",
  bold: "Editor",
  code: "Editor",
  delete: "Editor",
  dotpoints: "Editor",
  italic: "Editor",
  leftIndent: "Editor",
  letterSpacing: "Editor",
  lineHeight: "Editor",
  paragraphSpacing: "Editor",
  paragraphWrap: "Editor",
  rightIndent: "Editor",
  type: "Editor",
  typeStrikethrough: "Editor",
  underline: "Editor",
  write: "Editor",
  zoomIn: "Editor",
  zoomOut: "Editor",

  alertCircle: "Feedback",
  alertTriangle: "Feedback",
  bell: "Feedback",
  bellActive: "Feedback",
  bellOff: "Feedback",
  helpCircle: "Feedback",
  infoCircle: "Feedback",
  thumbsDown: "Feedback",
  thumbsUp: "Feedback",

  file: "Files",
  fileCheck: "Files",
  fileDownload: "Files",
  fileMinus: "Files",
  filePlus: "Files",
  fileSearch: "Files",
  fileText: "Files",
  fileX: "Files",
  folder: "Files",
  folderCheck: "Files",
  folderDownload: "Files",

  copy: "General",
  dotsVertical: "General",
  download: "General",
  downloadCloud: "General",
  home: "General",
  link: "General",
  lock: "General",
  logIn: "General",
  logOut: "General",
  menu: "General",
  search: "General",
  settings: "General",
  share: "General",
  sliders: "General",
  trash: "General",
  unlock: "General",
  uploadCloud: "General",

  arrowDown: "Interaction",
  arrowDownLeft: "Interaction",
  arrowDownRight: "Interaction",
  arrowLeft: "Interaction",
  arrowRight: "Interaction",
  arrowUp: "Interaction",
  arrowUpLeft: "Interaction",
  arrowUpRight: "Interaction",
  check: "Interaction",
  checkCircle: "Interaction",
  checkSquare: "Interaction",
  chevronDown: "Interaction",
  chevronLeft: "Interaction",
  chevronRight: "Interaction",
  chevronUp: "Interaction",
  flipBackward: "Interaction",
  flipForward: "Interaction",
  heart: "Interaction",
  plus: "Interaction",
  plusCircle: "Interaction",
  plusSquare: "Interaction",
  refresh: "Interaction",
  reply: "Interaction",
  switchHorizontal: "Interaction",
  switchVertical: "Interaction",
  xCircle: "Interaction",
  xClose: "Interaction",

  camera: "Media",
  cameraOff: "Media",
  cameraPlus: "Media",
  imagCheck: "Media",
  image: "Media",
  imageDown: "Media",
  imageLeft: "Media",
  imagePlus: "Media",
  imageRight: "Media",
  imageUp: "Media",
  power: "Media",
  repeat: "Media",
  video: "Media",
  videoOff: "Media",

  alarm: "Time",
  alarmCheck: "Time",
  alarmMinus: "Time",
  alarmOff: "Time",
  alarmPlus: "Time",
  CalendarDate: "Time",
  calendar: "Time",
  calendarCheck: "Time",
  calendarPlus: "Time",
  clock: "Time",
  clockCheck: "Time",
  clockPlus: "Time",
  clockSnooze: "Time",

  user: "Users",
  userCheck: "Users",
  userEdit: "Users",
  userMinus: "Users",
  userPlus: "Users",
  userX: "Users",
  users: "Users",
  usersCheck: "Users",
  usersMinus: "Users",
  usersPlus: "Users",
  usersX: "Users",

  Facebook: "Logo",
  apple: "Logo",
  behance: "Logo",
  github: "Logo",
  googleColor: "Logo",
  googleMono: "Logo",
  instagram: "Logo",
  kakao: "Logo",
  linkedin: "Logo",
  playstore: "Logo",
};

/**
 * 피그마 type 값에서 발견된 오타/대소문자 불일치를 코드 사이드에서 보정한다.
 * 디자이너가 추후 피그마에서 정정하면 이 매핑에서 해당 항목만 제거하면 됨.
 */
export const FIGMA_NAME_OVERRIDES: Record<string, string> = {
  mesageCheck: "messageCheck",
  imagCheck: "imageCheck",
  CalendarDate: "calendarDate",
  Facebook: "facebook",
};

export const getCorrectedName = (figmaType: string): string =>
  FIGMA_NAME_OVERRIDES[figmaType] ?? figmaType;
